// <auto-generated />
using API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace API.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20190803220956_agregarCampoValorTotal")]
    partial class agregarCampoValorTotal
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024");

            modelBuilder.Entity("API.Model.Usuario", b =>
                {
                    b.Property<int>("UsuarioId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Token");

                    b.Property<double>("ValorTotal");

                    b.HasKey("UsuarioId");

                    b.ToTable("Usuario");
                });

            modelBuilder.Entity("API.Model.Valor", b =>
                {
                    b.Property<int>("ValorId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Operacion");

                    b.Property<string>("Signo");

                    b.Property<int>("UsuarioId");

                    b.Property<double>("ValorOperacion");

                    b.HasKey("ValorId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Valor");
                });

            modelBuilder.Entity("API.Model.Valor", b =>
                {
                    b.HasOne("API.Model.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
